name: CI
on: [push]
jobs:
  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Download build dependencies
      run: make download-deps

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc-i686-linux-gnu binutils-i686-linux-gnu gcc-arm-none-eabi grub-common

    - name: Update build config for CI
      run: |
        sed -i 's/deps\/coreboot\/util\/crossgcc\/xgcc\/bin\/i386-elf-gcc/i686-linux-gnu-gcc/g' config/build_x86.cfg
        sed -i 's/deps\/coreboot\/util\/crossgcc\/xgcc\/bin\/i386-elf-objcopy/i686-linux-gnu-objcopy/g' config/build_x86.cfg
        sed -i 's/deps\/coreboot\/util\/crossgcc\/xgcc\/bin\/arm-eabi-gcc/arm-none-eabi-gcc/g' config/build_arm.cfg
        sed -i 's/deps\/coreboot\/util\/crossgcc\/xgcc\/bin\/arm-eabi-as/arm-none-eabi-as/g' config/build_arm.cfg
        sed -i 's/deps\/coreboot\/util\/crossgcc\/xgcc\/bin\/arm-eabi-objcopy/arm-none-eabi-objcopy/g' config/build_arm.cfg

    - name: Build Odyssey (x86)
      run: make

    - name: Build ISO
      run: make iso

    - uses: actions/upload-artifact@v2
      with:
        name: odyssey.iso
        path: odyssey.iso

    - name: Clean workspace
      run: make clean

    - name: Build Odyssey (arm)
      run: make ARCH=arm
