name: CI
on: [push]
jobs:
  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:

    - name: Build dependencies
      run: make download-deps

    - name: Build Odyssey (x86)
      run: make

    - name: Clean workspace
      run: make clean

    - name: Build Odyssey (arm)
      run: make ARCH=arm
